all:
		g++ -g  -std=c++11  -Wextra -pedantic -Wwrite-strings -Wall readerProgram.cpp  -o readerProgram 
		g++ -g -std=c++11  -Wextra -pedantic -Wwrite-strings -Wall writerProgram.cpp  -o writerProgram
