all:
	gcc -Wall -g systemInfo.c -o systemInfo
	./systemInfo
	
#	valgrind --leak-check=full ./systemInfo

# when pushing to get hub follow the following  
# git commit -m "message"
# git add /lab1
# git push -u orgin master
# git remote add origin https://github.com/hendrash/cis452.git 
